### ISSUE TITLE
Allow specifying cluster version

### ISSUE THREAD

**Issue by abayer** [jenkins-x/terraform-google-jx#102] opened 2020-06-03 16:17 UTC
I believe this should be possible to add, but as of now, we always use the default version, and it'd be good to allow that to be overridden.

Relates to https://github.com/jenkins-x/jx/issues/6957

**Comment by hferentschik** [comment] 2020-06-03 16:59
Closing this as duplicate of #98 ;-)

**Closed by hferentschik** 2020-06-03 16:59 UTC
Labels: area/terraform, kind/feature

**Comment by abayer** [comment] 2020-06-03 17:02
Well, I feel silly. =)
