### ISSUE TITLE
Allow specifying backup bucket location

### ISSUE THREAD

**Issue by joostvdg** [jenkins-x/terraform-google-jx#90] opened 2020-05-06 21:20 UTC
It seems I cannot specify the location of the bucket for the backups: https://github.com/jenkins-x/terraform-google-jx/blob/master/modules/backup/main.tf#L7

I do not see an option. And when I plan I get the following:

```terraform
# module.jx.module.backup.google_storage_bucket.backup_bucket will be created
  + resource "google_storage_bucket" "backup_bucket" {
      + bucket_policy_only = (known after apply)
      + force_destroy      = false
      + id                 = (known after apply)
      + location           = "US"
      + name               = (known after apply)
      + project            = (known after apply)
      + self_link          = (known after apply)
      + storage_class      = "STANDARD"
      + url                = (known after apply)
    }
```

```
      + location           = "US"
```

As EU citizen, I generally want to store my data in the EU, or at least have the option to. See: https://cloud.google.com/storage/docs/locations

**Comment by hferentschik** [comment] 2020-06-02 09:53
Duplicate of issue #66.

**Closed by hferentschik** 2020-06-02 09:53 UTC
Labels: area/terraform, in progress, kind/feature
